#!/usr/bin/env python3
"""
Promote the weights train.tl just produced into the tracked, in-repo
"production" location that infer.tl actually loads from:

    cache/apps/games/2048/train.tl/weights/*.npy   (train.tl's scratch output)
        --promote-->
    apps/games/2048/weights/*.npy                  (tracked; infer.tl reads this)

Run after a training run you're happy with:

    python3 apps/games/2048/tools/promote_weights.py
    # or: ./apps/games/2048/run.sh --promote

WHY THIS EXISTS: train.tl's own output lives under cache/, same as every
other .tl file's load()/save() scratch space in this repo (see
tensorlang/compiler.py — save() resolves relative paths against that
per-file cache directory). That's the right default for something that
gets regenerated by re-running a subprocess, but a set of trained
weights is different: it took ~1 hour of real GPU time to produce, cache/
isn't tracked in git (same as tic_tac_toe — see NOTES.md), and run.sh
--train's own "skip init if weights already exist" logic means a
half-considered retrain can silently warm-start from — or, if you
manually rm -rf first, permanently destroy — whatever was there before,
with no way back. This script is the one deliberate checkpoint action
that separates "training experiment" (freely repeatable, no consequences
to anything tracked) from "this is the version the game actually uses
now" (an explicit, backed-up act).

BACKUP: if apps/games/2048/weights/ already has a promoted set of
weights, they're moved to apps/games/2048/weights/.previous/ first
(overwriting any earlier .previous/ backup — this is a single rollback
slot, not a full history; once you've committed a promoted set of
weights, git itself is your real history). See rollback_weights.py to
restore from that backup.
"""
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
from tlkit import chunked_runner  # noqa: E402

WEIGHT_FILES = ["w1.npy", "b1.npy", "w2.npy", "b2.npy", "w3.npy", "b3.npy"]


def main():
    repo_root = chunked_runner.find_repo_root()
    src_dir = repo_root / "cache" / "apps" / "games" / "2048" / "train.tl" / "weights"
    dst_dir = repo_root / "apps" / "games" / "2048" / "weights"
    backup_dir = dst_dir / ".previous"

    missing = [f for f in WEIGHT_FILES if not (src_dir / f).exists()]
    if missing:
        print(f"ERROR: {src_dir} is missing {missing} — run ./run.sh --train first.")
        sys.exit(1)

    existing = [f for f in WEIGHT_FILES if (dst_dir / f).exists()]
    if existing:
        backup_dir.mkdir(parents=True, exist_ok=True)
        for f in existing:
            shutil.copy2(dst_dir / f, backup_dir / f)
        print(f"Backed up current {dst_dir} -> {backup_dir} "
              f"(overwrote any earlier backup — single rollback slot).")
    else:
        print(f"{dst_dir} is empty (first promotion) — nothing to back up.")

    dst_dir.mkdir(parents=True, exist_ok=True)
    for f in WEIGHT_FILES:
        shutil.copy2(src_dir / f, dst_dir / f)

    print(f"Promoted {src_dir} -> {dst_dir}")
    print("infer.tl (and therefore agent.py's choose_ai_move) will use these from now on.")
    print(f"If you want this checked in: git add {dst_dir.relative_to(repo_root)}")


if __name__ == "__main__":
    main()
